#!/bin/bash
echo "sorting out MTU"
ifconfig eth0 mtu 1400

(
cat <<'EOP'
MTU=1400
EOP
) >> /etc/sysconfig/network-scripts/ifcfg-eth0

rpm -Uvh http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-4.noarch.rpm
sudo wget -O /etc/yum.repos.d/aegis.repo http://rpm.aegisco.com/aegisco/el5/aegisco.repo
rpm -Uvh http://download.elff.bravenet.com/5/i386/elff-release-5-3.noarch.rpm

yum install -q -y make gcc gcc-c++ zlib-devel openssl-devel readline-devel sqlite-devel git automake autoconf make gcc44 gcc44-c++

ln -sf /usr/bin/gcc44 /usr/bin/gcc
ln -sf /usr/bin/g++44 /usr/bin/g++

#Install ruby
cd /tmp
wget http://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7.tar.gz
tar zxf ruby-1.8.7.tar.gz
cd /tmp/ruby-1.8.7
./configure --with-openssl-dir=/usr/lib/openssl
make
make install
ln -sf /usr/local/bin/ruby /usr/bin/ruby

#Install rubygems
cd /tmp
wget http://production.cf.rubygems.org/rubygems/rubygems-1.7.2.tgz
tar zxf rubygems-1.7.2.tgz
cd rubygems-1.7.2
sudo ruby setup.rb --no-format-executable

sudo gem install chef ohai --no-rdoc --no-ri

mkdir /etc/chef

(
cat <<'EOP'
file_cache_path "/tmp/chef-solo"
cookbook_path "/tmp/chef-solo/cookbooks"
EOP
) > /etc/chef/solo.rb

(
cat <<'EOP'
{
  "chef_server": {
    "server_url": "http://localhost:4000",
    "webui_enabled": true,
    "init_style": "init"
  },
  "run_list": [ "recipe[chef-server::rubygems-install]" ]
}
EOP
) > ~/.chef.json

chef-solo -c /etc/chef/solo.rb -j ~/chef.json -r http://s3.amazonaws.com/chef-solo/bootstrap-latest.tar.gz
