#!/bin/bash
echo "sorting out MTU"
ifconfig eth0 mtu 1400

(
cat <<'EOP'
MTU=1400
EOP
) >> /etc/sysconfig/network-scripts/ifcfg-eth0

/etc/init.d/network restart

export PATH=/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:$PATH

rpm -Uvh http://download.fedora.redhat.com/pub/epel/5/i386/epel-release-5-4.noarch.rpm
rpm -Uvh http://download.elff.bravenet.com/5/i386/elff-release-5-3.noarch.rpm

echo "starting package install"

yum install -q -y make gcc gcc-c++ zlib-devel openssl-devel readline-devel sqlite-devel

echo "finished package install"

cd /tmp
wget http://ftp.ruby-lang.org/pub/ruby/1.8/ruby-1.8.7.tar.gz
tar zxf ruby-1.8.7.tar.gz
cd /tmp/ruby-1.8.7
./configure --with-openssl-dir=/usr/lib/openssl
make
make install
ln -sf /usr/local/bin/ruby /usr/bin/ruby

cd /tmp
wget http://production.cf.rubygems.org/rubygems/rubygems-1.7.2.tgz
tar zxf rubygems-1.7.2.tgz
cd rubygems-1.7.2
ruby setup.rb --no-format-executable

gem update --system

gem install ohai chef --no-rdoc --no-ri --verbose 

yum install -y gcc44 gcc44-c++

ln -sf /usr/bin/gcc44 /usr/bin/gcc
ln -sf /usr/bin/g++44 /usr/bin/g++
ln -sf /usr/local/bin/chef-solr /usr/bin/chef-solr
ln -sf /usr/local/bin/chef-server /usr/bin/chef-server
ln -sf /usr/local/bin/chef-server-webui /usr/bin/chef-server-webui
ln -sf /usr/local/bin/chef-expander /usr/bin/chef-expander

mkdir -p /etc/chef

(
cat <<'EOP'
file_cache_path "/tmp/chef-solo"
cookbook_path "/tmp/chef-solo/cookbooks"
EOP
) > /etc/chef/solo.rb

(
cat <<'EOP'
{
  "chef_server": {
    "server_url": "http://localhost:4000",
    "webui_enabled": true,
    "init_style": "init"
  },
  "run_list": [ "recipe[chef-server::rubygems-install]" ]
}
EOP
) > ~/chef.json

# NOTE:  This bit of the script fails the first time it is run.  It compains about some group not exisiting
# I have found thatif you just run it again then it works!  Can't be bothered to figure this out now so just run this twice.
chef-solo -c /etc/chef/solo.rb -j ~/chef.json -r http://s3.amazonaws.com/chef-solo/bootstrap-latest.tar.gz
