#!/bin/bash
echo "sorting out MTU"
ifconfig eth0 mtu 1400

(
cat <<'EOP'
MTU=1400
EOP
) >> /etc/sysconfig/network-scripts/ifcfg-eth0
/etc/init.d/network restart

(
cat <<'EOP'
deb http://uk.archive.ubuntu.com/ubuntu/ lucid main restricted universe multiverse 
deb-src http://uk.archive.ubuntu.com/ubuntu/ lucid main restricted universe multiverse
EOP
) >> /etc/apt/sources.list

apt-get update

sudo apt-get install -y ruby ruby-dev libopenssl-ruby rdoc ri irb build-essential wget ssl-cert

echo "finished package install"

cd /tmp
wget http://production.cf.rubygems.org/rubygems/rubygems-1.7.2.tgz
tar zxf rubygems-1.7.2.tgz
cd rubygems-1.7.2
ruby setup.rb --no-format-executable

gem update --system

gem install ohai chef --no-rdoc --no-ri --verbose 

mkdir -p /etc/chef

(
cat <<'EOP'
file_cache_path "/tmp/chef-solo"
cookbook_path "/tmp/chef-solo/cookbooks"
EOP
) > /etc/chef/solo.rb

(
cat <<'EOP'
{
  "chef_server": {
    "server_url": "http://localhost:4000",
    "webui_enabled": true
  },
  "run_list": [ "recipe[chef-server::rubygems-install]" ]
}
EOP
) > ~/chef.json

chef-solo -c /etc/chef/solo.rb -j ~/chef.json -r http://s3.amazonaws.com/chef-solo/bootstrap-latest.tar.gz
