#!/usr/bin/env ruby
#
require "cloud"
require "chef_server"

cloud = Cloud.new
puts "creating keys to access servers"
cloud.create_keypair "chef_keyfile"

puts "creating security group to access servers"
cloud.create_security_group "chef-group"

puts "Spinning up servers"
servers = cloud.create_servers(5)

webserver1 = servers[0]
webserver2 = servers[1]
loadbalancer1 = servers[2]
loadbalancer2 = servers[3]
database = servers[4]

chef = ChefServer.new
chef.configure_chef

chef.bootstrap(database.dns_name, database.id, ["role[cdd_primary_db_server]"], "/tmp/chef_keyfile")
chef.bootstrap(webserver1.dns_name, webserver1.id, ["role[cdd_app_server]"], "/tmp/chef_keyfile")
chef.bootstrap(webserver2.dns_name, webserver2.id, ["role[cdd_app_server]"], "/tmp/chef_keyfile")
chef.bootstrap(loadbalancer1.dns_name, loadbalancer1.id, ["role[cdd_loadbalancer]"], "/tmp/chef_keyfile")

puts "Your new cluster is available at #{loadbalancer1.dns_name} - enjoy"

