#!/usr/bin/env ruby
#
Bundler.require
require "cloud"
require "chef_server"
KEYNAME = "chef_server_keyfile"
KEYFILE = "/tmp/#{KEYNAME}"
IMAGE = "pmi-a14d20a6" #centos
#IMAGE = "pmi-09a4d943" #ubuntu
INSTALL_SCRIPT_NAME = "install_chef_server_centos"

cloud = Cloud.new
puts "creating keys to access servers"
cloud.create_keypair KEYNAME

puts "creating security group to access servers"
cloud.create_security_group "chef-server-group"

puts "Spinning up servers"
servers = cloud.create_servers(1, IMAGE)

chefserver = servers.first

Net::SCP.upload!(chefserver.dns_name,
                 "root",
                 "./#{INSTALL_SCRIPT_NAME}",
                 "/tmp/#{INSTALL_SCRIPT_NAME}",
                 :ssh => {:auth_methods => %w(publickey),:keys => KEYFILE },
                 :recursive => true, :paranoid => false )


Net::SSH.start(chefserver.dns_name, "root", :auth_methods => %w(publickey),:keys => KEYFILE, :timeout => 600, :paranoid => false) do |ssh|
  ssh.exec! "chmod a+x /tmp/#{INSTALL_SCRIPT_NAME}"
  ssh.exec! "/tmp/#{INSTALL_SCRIPT_NAME} > /tmp/install.log &2>1"
end

puts "Your new chef server is available at #{chefserver.dns_name} - enjoy"

